version: '3.8'

services:
  confluence-api-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Optional: Configure via environment variables
      # CONFLUENCE_BASE_URL: "https://your-domain.atlassian.net"
      # CONFLUENCE_EMAIL: "your-email@example.com"
      # CONFLUENCE_API_TOKEN: "your-api-token"
      - LOG_LEVEL=info
    volumes:
      # Mount for development (uncomment for live reloading)
      # - .:/app
      - /dev/null:/app/.env  # Prevent .env file conflicts
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

